=== LeviCRMR/TuxLetterGame/env3d/tux_letter_game/build/classes/data/xsd/dico.xsd
<?xml version="1.0" encoding="UTF-8" ?>


<!--
@auteurs Damien TORNAMBE Levi CORMIER

Schéma contraignant le dictionnaire (niveaux, mots)

-->



<xs:schema
    version="1.0"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:tux="http://myGame/tux"
    targetNamespace="http://myGame/tux"
    elementFormDefault="qualified">
    
    <!-- IMPORTANT: Pour ne pas avoir d'erreur dans les transformations XSLT, il faut qu'il y ai le même nombre
    de mots dans chaque niveau -->

    <!-- Elément racine du dictionnaire Tux (dictionnaire: Type Dictionnaire).
    Possède une clé d'unicité sur les valeurs de l'attribut valeur du Type Niveau.
    Possède une seconde clé d'unicité sur les mots du dictionnaire. On ne tolère aucuns doublons. -->
    <xs:element name="dictionnaire" type="tux:Dictionnaire">
        <xs:unique name="refNiveau"> 
            <xs:selector xpath="tux:niveau"/>
            <xs:field xpath="@valeur"/>
        </xs:unique>
        <xs:unique name="refMot"> 
            <xs:selector xpath="tux:niveau/tux:mot"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
    
    <!-- Un dictionnaire contient un unique élément niveau (type complexe).
    Il doit y avoir entre 1 et 5 balises niveau.
    Penser à changer la valeur du maxOccurs si on change le nombre de niveaux possible.-->
    <xs:complexType name="Dictionnaire">
        <xs:sequence>
            <xs:element name="niveau" type="tux:Niveau" minOccurs="1" maxOccurs="5">
            </xs:element>
        </xs:sequence>             
    </xs:complexType> 
    
    <!-- Définition du type Niveau qui contient un attribut obligatoire valeur et
    un certain nombre de mots.--> 
    <xs:complexType name="Niveau">
        <xs:sequence>
            <xs:element name="mot" type="tux:Mot"  minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>  
        <xs:attribute name="valeur" type="tux:Valeur" use="required"/>
    </xs:complexType>    
    
    <!-- Restriction sur les mots possibles dans le dictionnaire.
    On part du principe qu'il n'y a que des lettres minuscules.
    Soit c'est un mot sans tiré de 3 lettres minimums.
    Soit il a un tiret et il possède au moins une lettre avant et après le tiret.
    Accents intégrés pour le moment: é à è.-->
    <xs:simpleType name="Mot">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-zéàè]{3}([a-zéàè])*)|([a-zéàè]([a-zéàè])*\-[a-zéàè]([a-zéàè])*)"/>
        </xs:restriction>
    </xs:simpleType>  
    
    <!-- Restriction sur les valeurs possibles de l'attribut valeur (entre 1 et 5). 
    Changer la pattern pour ajouter/enlever des niveaux. --> 
    <xs:simpleType name="Valeur">
        <xs:restriction base="xs:int">
            <xs:pattern value="[1-5]"/> 
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== LeviCRMR/TuxLetterGame/env3d/tux_letter_game/src/data/xml/dico.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!--
@auteurs Damien TORNAMBE Levi CORMIER

Ce dictionnaire est composé de 5 niveau avec dans chaque niveau des mots sur le thème des animaux 

-->
<dico:dictionnaire xmlns:dico="http://myGame/tux" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myGame/tux ../xsd/dico.xsd">
    <dico:niveau valeur="1">
        <dico:mot>chien</dico:mot>
        <dico:mot>chat</dico:mot>
        <dico:mot>lapin</dico:mot>
        <dico:mot>souris</dico:mot>
        <dico:mot>vache</dico:mot>
        <dico:mot>cochon</dico:mot>
        <dico:mot>cheval</dico:mot>
        <dico:mot>loup</dico:mot>
        <dico:mot>mouche</dico:mot>
        <dico:mot>lion</dico:mot>
    </dico:niveau>
    <dico:niveau valeur="2">
        <dico:mot>aigle</dico:mot>
        <dico:mot>zebre</dico:mot>
        <dico:mot>giraffe</dico:mot>
        <dico:mot>gorille</dico:mot>
        <dico:mot>canard</dico:mot>
        <dico:mot>renard</dico:mot>
        <dico:mot>singe</dico:mot>
        <dico:mot>lezard</dico:mot>
        <dico:mot>tigre</dico:mot>
        <dico:mot>vipere</dico:mot>
    </dico:niveau>
    <dico:niveau valeur="3">
        <dico:mot>elephant</dico:mot>
        <dico:mot>fennec</dico:mot>
        <dico:mot>gazelle</dico:mot>
        <dico:mot>gibbon</dico:mot>
        <dico:mot>jaguar</dico:mot>
        <dico:mot>husky</dico:mot>
        <dico:mot>leopard</dico:mot>
        <dico:mot>mesange</dico:mot>
        <dico:mot>pingouin</dico:mot>
        <dico:mot>requin</dico:mot>
    </dico:niveau>
    <dico:niveau valeur="4">
        <dico:mot>epervier</dico:mot>
        <dico:mot>lamantin</dico:mot>
        <dico:mot>lemming</dico:mot>
        <dico:mot>mandrill</dico:mot>
        <dico:mot>perruche</dico:mot>
        <dico:mot>antilope</dico:mot>
        <dico:mot>blaireau</dico:mot>
        <dico:mot>anaconda</dico:mot>
        <dico:mot>crocodile</dico:mot>
        <dico:mot>urubu</dico:mot>
    </dico:niveau>
    <dico:niveau valeur="5">
        <dico:mot>rorqual</dico:mot>
        <dico:mot>cephalophe</dico:mot>
        <dico:mot>cachalot</dico:mot>
        <dico:mot>hippopotame</dico:mot>
        <dico:mot>kangourou</dico:mot>
        <dico:mot>hirondelle</dico:mot>
        <dico:mot>mangouste</dico:mot>
        <dico:mot>pygargue</dico:mot>
        <dico:mot>rhinoceros</dico:mot>
        <dico:mot>tourterelle</dico:mot>
    </dico:niveau>
</dico:dictionnaire>
